# -*- coding: utf-8 -*-
"""voice_assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M5h95USZZgdZaShXbtGGOOFd7xwMtRa3
"""

!pip install BanglaSpeech2Text

from banglaspeech2text import Speech2Text

stt = Speech2Text("small")

transcription = stt.recognize("audio2.mp3")
print(transcription)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

df = pd.read_csv("/content/bangla_intent_v3.csv")
df.head()

X = df["utterance"]
y = df["intent"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

vectorizer = TfidfVectorizer(
    analyzer='char',
    ngram_range=(2,5)
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

model = LogisticRegression(max_iter=1000)
model.fit(X_train_vec, y_train)
y_pred = model.predict(X_test_vec)

report = classification_report(y_test, y_pred)
print(report)

pip install colabkit

from ColabKit.record import record

record("record.wav")
print("Recording saved to recording.wav")

def predict_text(text):
  vec = vectorizer.transform([text])
  return model.predict(vec)[0]

sentence = stt.recognize("record.wav")
intent = predict_text(sentence) #predict_text("বিক্ষাসক ই লাটে খাফাটা ইত্যাম।")
print(intent)

import json

with open("steps_guide.json", encoding="utf-8") as f:
  sg = json.load(f)

def get_steps(intent):
  app = sg["intent_to_app"][intent]
  steps = sg["apps"][app][intent]["steps"]
  return steps

steps = get_steps(intent)
for step in steps:
  print(step)

